### ISSUE TITLE
support react 0.49, ES6

### ISSUE THREAD

**Issue by tranquan** [danleveille/react-native-input-accessory-demo#4]
Thanks  you for the code : )
I refactor it a bits to work with new react native ES6
[https://gist.github.com/tranquan/6b7f49a9831eaedd7d9fee765fa469fe](https://gist.github.com/tranquan/6b7f49a9831eaedd7d9fee765fa469fe)

**Comment by danleveille** [comment]
@tranquan Awesome! Please make a pull request. 😄
